services:
  smb-s3:
    build: .
    container_name: smb-s3-server
    privileged: true
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_REGION=${AWS_REGION:-auto}
      - S3_BUCKET=${S3_BUCKET}
    ports:
      - "445:445"
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
